name: Go Test and Coverage

on:
  push:
    branches: [ main ]

jobs:
  create:
    name: Run tests and upload coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get dependencies
        run: go get -v -t -d ./...
        env:
          GO111MODULE: "auto"

      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          fail_ci_if_error: true
